In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../DATA/DeepLearning/bank_note_data.txt', delimiter=',')

In [3]:
len(data)

1372

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [13]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(X_train)

MinMaxScaler()

In [17]:
scaled_X_train = scaler_object.transform(X_train)

In [18]:
scaled_X_test = scaler_object.transform(X_test)

In [19]:
X_train.max()

17.9274

In [20]:
scaled_X_train.max()

1.0000000000000002

In [21]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [22]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
# from keras.models import Sequential
# from keras.layers import Dense

In [28]:
from keras.models import Sequential
from keras.layers import Dense
# Creates model
model = Sequential()

# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))

# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))

# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

In [29]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
# Play around with number of epochs as well gone through data!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6959 - accuracy: 0.3569 - 1s/epoch - 39ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6885 - accuracy: 0.7541 - 76ms/epoch - 3ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6828 - accuracy: 0.8390 - 68ms/epoch - 2ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6799 - accuracy: 0.8781 - 60ms/epoch - 2ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6762 - accuracy: 0.8901 - 56ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6716 - accuracy: 0.8738 - 62ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6650 - accuracy: 0.8857 - 54ms/epoch - 2ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6574 - accuracy: 0.8215 - 56ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6505 - accuracy: 0.8030 - 62ms/epoch - 2ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6430 - accuracy: 0.8009 - 51ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6349 - accuracy: 0.7954 - 61ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.6262 - accuracy: 0.8009 - 54ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.6171 

In [40]:
# model.predict_classes(scaled_X_test)

In [32]:
model.metrics_names

['loss', 'accuracy']

In [45]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 [==============================] - 0s 2ms/step - loss: 0.2733 - accuracy: 0.9404


[0.27328816056251526, 0.940397322177887]

In [50]:
from sklearn.metrics import confusion_matrix,classification_report

In [53]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 2ms/step


In [54]:
predictions

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [55]:
confusion_matrix(y_test,predictions)

array([[241,  16],
       [ 11, 185]], dtype=int64)

In [57]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.94      0.95       257
         1.0       0.92      0.94      0.93       196

    accuracy                           0.94       453
   macro avg       0.94      0.94      0.94       453
weighted avg       0.94      0.94      0.94       453



In [58]:
model.save('myfirstmodel.h5')

In [59]:
from keras.models import load_model

In [60]:
newmodel = load_model('myfirstmodel.h5')

In [63]:
(newmodel.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 1ms/step


array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    